baseURL= "/"
languageCode= "fr_FR"
title= "hugo quickstart v2"
paginate = 5
copyright = "Tous droits réservés - 2018"
theme = "casper"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  description = "Bien démarrer avec Hugo"
  metadescription = "Utilisé dans la balise meta 'description' pour l’accueil et les pages d’index, faute de quoi c'est l’entrée 'description' du front matter de la page qui sera utilisé."
  cover = ""
  author = "Benjamin SICARD"
  authorlocation = "Paris, France"
  authorwebsite = ""
  authorbio= ""
  logo = ""
  hjsStyle = "default"
  paginatedsections = ["posts"]